
# ======================================================== #
# File automagically generated by GUI2Exe version 0.5.0
# Copyright: (c) 2007-2009 Andrea Gavana
# ======================================================== #

# Let's start with some default (for me) imports...

from distutils.core import setup
# original line: from py2exe.build_exe import py2exe
import py2exe

import glob
import os
# import zlib
import shutil
# import numpy

# Remove the build folder
shutil.rmtree("build", ignore_errors=True)


class Target(object):
    """ A simple class that holds information on our executable file. """
    def __init__(self, **kw):
        """ Default class constructor. Update as you need. """
        self.__dict__.update(kw)


# Ok, let's explain why I am doing that.
# Often, data_files, excludes and dll_excludes (but also resources)
# can be very long list of things, and this will clutter too much
# the setup call at the end of this file. So, I put all the big lists
# here and I wrap them using the textwrap module.

mfcdir = '.\\Microsoft.VC90.MFC'
mfcfiles = [os.path.join(mfcdir, i) for i in ["mfc90.dll", "mfc90u.dll", "mfcm90.dll", "mfcm90u.dll", "Microsoft.VC90.MFC.manifest"]]
 
crtdir = '.\\Microsoft.VC90.CRT'
crtfiles = [os.path.join(crtdir, i) for i in ['msvcr90.dll', 'Microsoft.VC90.CRT.manifest']]
 
data_files = [('Microsoft.VC90.CRT', crtfiles),
              ('Microsoft.VC90.MFC', mfcfiles)]
              #('.', ['.\\cps_dte.xrc'])]

# includes = ['win32gui', 'win32ui', 'win32con']
# includes = ['win32gui', 'win32ui', 'win32con', 'zope.interface']
includes = []
excludes = ['_gtkagg', '_tkagg', 'curses', 'difflib', 'doctest', 'email',
            'pdb', 'pygments', 'pyreadline', 'pywin.debugger',
            'pywin.debugger.dbgcon', 'pywin.dialogs', 'tcl', 'unittest']
#packages = ['wx', 'wx.lib']
packages = ['Tkinter', 'ttk','tkFileDialog']
dll_excludes = ['libgdk-win32-2.0-0.dll', 'libgobject-2.0-0.dll', 'mpr.dll',
                'msvcp90.dll', 'mswsock.dll', 'powrprof.dll',
                'tcl84.dll', 'tk84.dll']
icon_resources = []
bitmap_resources = []
other_resources = []


# This is a place where the user custom code may go. You can do almost
# whatever you want, even modify the data_files, includes and friends
# here as long as they have the same variable name that the setup call
# below is expecting.

# No custom code added


# Ok, now we are going to build our target class.
# I chose this building strategy as it works perfectly for me :-D

from settings import APP_VERSION, VENDOR_NAME

GUI2Exe_Target_1 = Target(
    # what to build
    script = "LogMonitorOverview.py",
    icon_resources = icon_resources,
    bitmap_resources = bitmap_resources,
    other_resources = other_resources,
    dest_base = "LogMonitorOverview",
    version = APP_VERSION,
    company_name = VENDOR_NAME,
    copyright = "Copyright (C) 2018",
    name = "Log Monitor Tool",
    )

# No custom class for UPX compression or Inno Setup script

# That's serious now: we have all (or almost all) the options py2exe
# supports. I put them all even if some of them are usually defaulted
# and not used. Some of them I didn't even know about.

setup(

    # No UPX or Inno Setup

    data_files = data_files,

    options = {"py2exe": {"compressed": 2,
                          "optimize": 2,
                          "includes": includes,
                          "excludes": excludes,
                          "packages": packages,
                          "dll_excludes": dll_excludes,
                          "bundle_files": 3,
                          "dist_dir": "dist",
                          "xref": False,
                          "skip_archive": False,
                          "ascii": False,
                          "custom_boot_script": '',
                         }
              },

    zipfile = None,
    console = [],
    windows = [GUI2Exe_Target_1],
    service = [],
    com_server = [],
    ctypes_com_server = []
    )

# This is a place where any post-compile code may go.
# You can add as much code as you want, which can be used, for example,
# to clean up your folders or to do some particular post-compilation
# actions.

# No post-compilation code added


# And we are done. That's a setup script :-D